# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ping',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='ping',
            name='requester',
        ),
    ]
