# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_auto_20160826_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ping',
            name='priority',
            field=models.BooleanField(),
        ),
    ]
