# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20160827_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ping',
            name='description',
            field=models.CharField(max_length=45),
        ),
    ]
