# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_auto_20160828_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ping',
            name='status',
        ),
        migrations.AddField(
            model_name='ping',
            name='slug',
            field=models.SlugField(default='abc', unique=True),
            preserve_default=False,
        ),
    ]
